{
 "title": "Pizza Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(sum_over_time(requests_ratio{source=\"jwt-pizza-service\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (method) (\r\n  sum_over_time(requests_ratio{source=\"jwt-pizza-service\"}[$__interval])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "active_users_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentications/Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by(result) (sum_over_time(auth_attempt_ratio{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Tatency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(latency_milliseconds{source=\"jwt-pizza-service\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors returned/min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum by(status) (sum_over_time(error_codes_ratio[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(revenue_ratio{source=\"jwt-pizza-service\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Computer Stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpu_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Sell Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pizza/min" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/15", "type": "math" }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 12 },
   "targets": [
    {
     "expr": "sum by(status) (sum_over_time(pizza_creation_ratio{source=\"jwt-pizza-service\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "latency_tracked_endpoints_milliseconds{endpoint=\"pizzaCreation\", source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}